### PR TITLE
Mayhem Heroes Integration

### PR DESCRIPTION
**Pull request by capuanob**
Initial PR

### CODE REVIEW

**Review by xansec — CHANGES_REQUESTED** [review]
This looks like it has a lot of conflicts. Is it possible you forgot to rebase/sync with upstream?  Please make the requested changes.

**Comment by capuanob** [comment]
@xansec I just synced with remote, does this fix it on your end?

**Comment by xansec** [comment]
It looks like there's a nested Mayhem folder with maybe duplicate files. You also committed a crash file, which is a security concern. I would remove the crash file (and remove it from your commit history if possible), un-nest and de-duplicate any Mayhemfiles or Dockerfiles. You can see what I'm seeing on the `files` tab
https://github.com/mayhemheroes/tomlkit/pull/1/files

**Comment by capuanob** [comment]
@xansec Gotcha, I believe this has been fixed. I removed the sub-directory from the newest commit and used git-filter-repo to remove that crash file from all previous commits.

**Comment by xansec** [comment]
That's fine. Just open a new PR and it should be good to go.

**Pull request closed without merging**
